// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using seragenda;

#nullable disable

namespace seragenda.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20260219091105_ReplaceAgeWithDateNaissance")]
    partial class ReplaceAgeWithDateNaissance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LienViseeMaitrise", b =>
                {
                    b.Property<int>("IdViseeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_visee_fk");

                    b.Property<int>("IdViseesMaitriserFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_visees_maitriser_fk");

                    b.HasKey("IdViseeFk", "IdViseesMaitriserFk")
                        .HasName("lien_visee_maitrise_pkey");

                    b.HasIndex("IdViseesMaitriserFk");

                    b.ToTable("lien_visee_maitrise", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Abonnement", b =>
                {
                    b.Property<int>("IdAbonnement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_abonnement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAbonnement"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<int>("IdUserFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_fk");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut")
                        .HasDefaultValueSql("'Actif'::character varying");

                    b.Property<string>("TypeAbo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_abo");

                    b.HasKey("IdAbonnement")
                        .HasName("abonnement_pkey");

                    b.HasIndex("IdUserFk");

                    b.ToTable("abonnement", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.AppartenirViseeAptitude", b =>
                {
                    b.Property<int>("IdAppartenirViseeAptitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_appartenir_visee_aptitude");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAppartenirViseeAptitude"));

                    b.Property<int?>("IdAptitudeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_aptitude_fk");

                    b.Property<int>("IdCompetenceFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_competence_fk");

                    b.Property<int>("IdViseesMaitriserFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_visees_maitriser_fk");

                    b.HasKey("IdAppartenirViseeAptitude")
                        .HasName("appartenir_visee_aptitude_pkey");

                    b.HasIndex("IdAptitudeFk");

                    b.HasIndex("IdCompetenceFk");

                    b.HasIndex("IdViseesMaitriserFk");

                    b.ToTable("appartenir_visee_aptitude", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Aptitude", b =>
                {
                    b.Property<int>("IdAptitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aptitude");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAptitude"));

                    b.Property<string>("NomAptitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_aptitude");

                    b.HasKey("IdAptitude")
                        .HasName("aptitude_pkey");

                    b.ToTable("aptitude", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.CalendrierScolaire", b =>
                {
                    b.Property<int>("IdCalendrier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_calendrier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalendrier"));

                    b.Property<string>("AnneeScolaire")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("annee_scolaire")
                        .HasComputedColumnSql("\nCASE\n    WHEN (EXTRACT(month FROM date_debut) >= (8)::numeric) THEN (((EXTRACT(year FROM date_debut))::text || '-'::text) || ((EXTRACT(year FROM date_debut) + (1)::numeric))::text)\n    ELSE ((((EXTRACT(year FROM date_debut) - (1)::numeric))::text || '-'::text) || (EXTRACT(year FROM date_debut))::text)\nEND", true);

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("NomEvenement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_evenement");

                    b.Property<string>("TypeEvenement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_evenement");

                    b.HasKey("IdCalendrier")
                        .HasName("calendrier_scolaire_pkey");

                    b.ToTable("calendrier_scolaire", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Chapitre", b =>
                {
                    b.Property<int>("IdChapitre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_chapitre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChapitre"));

                    b.Property<int>("IdLivreFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_livre_fk");

                    b.Property<int>("NumeroChapitre")
                        .HasColumnType("integer")
                        .HasColumnName("numero_chapitre");

                    b.Property<int?>("PageDebut")
                        .HasColumnType("integer")
                        .HasColumnName("page_debut");

                    b.Property<string>("TitreChapitre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titre_chapitre");

                    b.HasKey("IdChapitre")
                        .HasName("chapitre_pkey");

                    b.HasIndex("IdLivreFk");

                    b.ToTable("chapitre", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Competence", b =>
                {
                    b.Property<int>("IdCompetence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_competence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompetence"));

                    b.Property<string>("NomCompetence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_competence");

                    b.HasKey("IdCompetence")
                        .HasName("competence_pkey");

                    b.ToTable("competence", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Cour", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cours");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<string>("CodeCours")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_cours");

                    b.Property<string>("CouleurAgenda")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("couleur_agenda");

                    b.Property<string>("NomCours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_cours");

                    b.Property<string>("PrefixCours")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix_cours");

                    b.HasKey("IdCours")
                        .HasName("cours_pkey");

                    b.HasIndex(new[] { "CodeCours" }, "cours_code_cours_key")
                        .IsUnique();

                    b.ToTable("cours", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.CoursNiveau", b =>
                {
                    b.Property<int>("IdCoursNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cours_niveau");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCoursNiveau"));

                    b.Property<int>("IdCoursFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours_fk");

                    b.Property<int>("IdNiveauFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau_fk");

                    b.Property<int>("IdProfFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_prof_fk");

                    b.HasKey("IdCoursNiveau")
                        .HasName("cours_niveau_pkey");

                    b.HasIndex("IdNiveauFk");

                    b.HasIndex("IdProfFk");

                    b.HasIndex(new[] { "IdCoursFk", "IdNiveauFk", "IdProfFk" }, "cours_niveau_id_cours_fk_id_niveau_fk_id_prof_fk_key")
                        .IsUnique();

                    b.ToTable("cours_niveau", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Domaine", b =>
                {
                    b.Property<int>("IdDom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dom");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDom"));

                    b.Property<int>("IdCoursNiveauFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours_niveau_fk");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.HasKey("IdDom")
                        .HasName("domaine_pkey");

                    b.HasIndex("IdCoursNiveauFk");

                    b.ToTable("domaine", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Livre", b =>
                {
                    b.Property<int>("IdLivre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_livre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLivre"));

                    b.Property<string>("Auteur")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("auteur");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.Property<string>("MaisonEdition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("maison_edition");

                    b.Property<string>("TitreLivre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titre_livre");

                    b.HasKey("IdLivre")
                        .HasName("livre_pkey");

                    b.HasIndex(new[] { "Isbn" }, "livre_isbn_key")
                        .IsUnique();

                    b.ToTable("livre", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_niveau");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNiveau"));

                    b.Property<string>("CodeNiveau")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code_niveau");

                    b.Property<string>("NomNiveau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_niveau");

                    b.HasKey("IdNiveau")
                        .HasName("niveau_pkey");

                    b.HasIndex(new[] { "CodeNiveau" }, "niveau_code_niveau_key")
                        .IsUnique();

                    b.ToTable("niveau", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.NomVisee", b =>
                {
                    b.Property<int>("IdNomVisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_nom_visee");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNomVisee"));

                    b.Property<string>("NomVisee1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nom_visee");

                    b.HasKey("IdNomVisee")
                        .HasName("nom_visee_pkey");

                    b.ToTable("nom_visee", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Planification", b =>
                {
                    b.Property<int>("IdPlanning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_planning");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanning"));

                    b.Property<DateOnly>("DateSeance")
                        .HasColumnType("date")
                        .HasColumnName("date_seance");

                    b.Property<TimeOnly?>("HeureDebut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("heure_debut");

                    b.Property<TimeOnly?>("HeureFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("heure_fin");

                    b.Property<int?>("IdCalendrierFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_calendrier_fk");

                    b.Property<int>("IdCoursNiveauFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours_niveau_fk");

                    b.Property<string>("NoteProf")
                        .HasColumnType("text")
                        .HasColumnName("note_prof");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut")
                        .HasDefaultValueSql("'Prévue'::character varying");

                    b.HasKey("IdPlanning")
                        .HasName("planification_pkey");

                    b.HasIndex("IdCalendrierFk");

                    b.HasIndex("IdCoursNiveauFk");

                    b.ToTable("planification", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.SeanceObjectif", b =>
                {
                    b.Property<int>("IdSeanceObj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seance_obj");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeanceObj"));

                    b.Property<bool?>("EvaluationPrevue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("evaluation_prevue");

                    b.Property<int>("IdPlanningFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_planning_fk");

                    b.Property<int>("IdViseeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_visee_fk");

                    b.HasKey("IdSeanceObj")
                        .HasName("seance_objectif_pkey");

                    b.HasIndex("IdPlanningFk");

                    b.HasIndex("IdViseeFk");

                    b.ToTable("seance_objectif", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.SeanceRessource", b =>
                {
                    b.Property<int>("IdSeanceRes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seance_res");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeanceRes"));

                    b.Property<int>("IdChapitreFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_chapitre_fk");

                    b.Property<int>("IdPlanningFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_planning_fk");

                    b.HasKey("IdSeanceRes")
                        .HasName("seance_ressource_pkey");

                    b.HasIndex("IdChapitreFk");

                    b.HasIndex("IdPlanningFk");

                    b.ToTable("seance_ressource", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Sousdomaine", b =>
                {
                    b.Property<int>("IdSousDomaine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_sous_domaine");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSousDomaine"));

                    b.Property<int>("IdDomFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_dom_fk");

                    b.Property<string>("NomComp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_comp");

                    b.HasKey("IdSousDomaine")
                        .HasName("sousdomaine_pkey");

                    b.HasIndex("IdDomFk");

                    b.ToTable("sousdomaine", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<int>("IdUserFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_fk");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("user_course_pkey");

                    b.HasIndex("IdUserFk");

                    b.ToTable("user_course", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<int>("IdUserFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_fk");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("user_note_pkey");

                    b.HasIndex("IdUserFk");

                    b.ToTable("user_note", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("NomComplet")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nom_complet");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("RoleSysteme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role_systeme")
                        .HasDefaultValueSql("'PROF'::character varying");

                    b.HasKey("IdUser")
                        .HasName("utilisateur_pkey");

                    b.HasIndex(new[] { "Email" }, "utilisateur_email_key")
                        .IsUnique();

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.UtilisationChapitre", b =>
                {
                    b.Property<int>("IdUtilisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisation"));

                    b.Property<int>("IdChapitreFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_chapitre_fk");

                    b.Property<int>("IdCoursNiveauFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours_niveau_fk");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut")
                        .HasDefaultValueSql("'Recommandé'::character varying");

                    b.HasKey("IdUtilisation")
                        .HasName("utilisation_chapitre_pkey");

                    b.HasIndex("IdChapitreFk");

                    b.HasIndex("IdCoursNiveauFk");

                    b.ToTable("utilisation_chapitre", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.UtilisationLivre", b =>
                {
                    b.Property<int>("IdUtilisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisation"));

                    b.Property<int>("IdCoursNiveauFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_cours_niveau_fk");

                    b.Property<int>("IdLivreFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_livre_fk");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut")
                        .HasDefaultValueSql("'Recommandé'::character varying");

                    b.HasKey("IdUtilisation")
                        .HasName("utilisation_livre_pkey");

                    b.HasIndex("IdCoursNiveauFk");

                    b.HasIndex("IdLivreFk");

                    b.ToTable("utilisation_livre", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.Visee", b =>
                {
                    b.Property<int>("IdVisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_visee");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVisee"));

                    b.Property<int>("IdCompFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_comp_fk");

                    b.Property<int>("IdDomaineFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_domaine_fk");

                    b.Property<int>("IdNomViseeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_nom_visee_fk");

                    b.Property<int?>("IdSousDomaineFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_sous_domaine_fk");

                    b.HasKey("IdVisee")
                        .HasName("visees_pkey");

                    b.HasIndex("IdCompFk");

                    b.HasIndex("IdDomaineFk");

                    b.HasIndex("IdNomViseeFk");

                    b.HasIndex("IdSousDomaineFk");

                    b.ToTable("visees", (string)null);
                });

            modelBuilder.Entity("seragenda.Models.ViseesMaitriser", b =>
                {
                    b.Property<int>("IdViseesMaitriser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_visees_maitriser");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdViseesMaitriser"));

                    b.Property<string>("NomViseesMaitriser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_visees_maitriser");

                    b.HasKey("IdViseesMaitriser")
                        .HasName("visees_maitriser_pkey");

                    b.ToTable("visees_maitriser", (string)null);
                });

            modelBuilder.Entity("LienViseeMaitrise", b =>
                {
                    b.HasOne("seragenda.Models.Visee", null)
                        .WithMany()
                        .HasForeignKey("IdViseeFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lien_visee_maitrise_id_visee_fk_fkey");

                    b.HasOne("seragenda.Models.ViseesMaitriser", null)
                        .WithMany()
                        .HasForeignKey("IdViseesMaitriserFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lien_visee_maitrise_id_visees_maitriser_fk_fkey");
                });

            modelBuilder.Entity("seragenda.Models.Abonnement", b =>
                {
                    b.HasOne("seragenda.Models.Utilisateur", "IdUserFkNavigation")
                        .WithMany("Abonnements")
                        .HasForeignKey("IdUserFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("abonnement_id_user_fk_fkey");

                    b.Navigation("IdUserFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.AppartenirViseeAptitude", b =>
                {
                    b.HasOne("seragenda.Models.Aptitude", "IdAptitudeFkNavigation")
                        .WithMany("AppartenirViseeAptitudes")
                        .HasForeignKey("IdAptitudeFk")
                        .HasConstraintName("appartenir_visee_aptitude_id_aptitude_fk_fkey");

                    b.HasOne("seragenda.Models.Competence", "IdCompetenceFkNavigation")
                        .WithMany("AppartenirViseeAptitudes")
                        .HasForeignKey("IdCompetenceFk")
                        .IsRequired()
                        .HasConstraintName("appartenir_visee_aptitude_id_competence_fk_fkey");

                    b.HasOne("seragenda.Models.ViseesMaitriser", "IdViseesMaitriserFkNavigation")
                        .WithMany("AppartenirViseeAptitudes")
                        .HasForeignKey("IdViseesMaitriserFk")
                        .IsRequired()
                        .HasConstraintName("appartenir_visee_aptitude_id_visees_maitriser_fk_fkey");

                    b.Navigation("IdAptitudeFkNavigation");

                    b.Navigation("IdCompetenceFkNavigation");

                    b.Navigation("IdViseesMaitriserFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.Chapitre", b =>
                {
                    b.HasOne("seragenda.Models.Livre", "IdLivreFkNavigation")
                        .WithMany("Chapitres")
                        .HasForeignKey("IdLivreFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chapitre_id_livre_fk_fkey");

                    b.Navigation("IdLivreFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.CoursNiveau", b =>
                {
                    b.HasOne("seragenda.Models.Cour", "IdCoursFkNavigation")
                        .WithMany("CoursNiveaus")
                        .HasForeignKey("IdCoursFk")
                        .IsRequired()
                        .HasConstraintName("cours_niveau_id_cours_fk_fkey");

                    b.HasOne("seragenda.Models.Niveau", "IdNiveauFkNavigation")
                        .WithMany("CoursNiveaus")
                        .HasForeignKey("IdNiveauFk")
                        .IsRequired()
                        .HasConstraintName("cours_niveau_id_niveau_fk_fkey");

                    b.HasOne("seragenda.Models.Utilisateur", "IdProfFkNavigation")
                        .WithMany("CoursNiveaus")
                        .HasForeignKey("IdProfFk")
                        .IsRequired()
                        .HasConstraintName("cours_niveau_id_prof_fk_fkey");

                    b.Navigation("IdCoursFkNavigation");

                    b.Navigation("IdNiveauFkNavigation");

                    b.Navigation("IdProfFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.Domaine", b =>
                {
                    b.HasOne("seragenda.Models.CoursNiveau", "IdCoursNiveauFkNavigation")
                        .WithMany("Domaines")
                        .HasForeignKey("IdCoursNiveauFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("domaine_id_cours_niveau_fk_fkey");

                    b.Navigation("IdCoursNiveauFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.Planification", b =>
                {
                    b.HasOne("seragenda.Models.CalendrierScolaire", "IdCalendrierFkNavigation")
                        .WithMany("Planifications")
                        .HasForeignKey("IdCalendrierFk")
                        .HasConstraintName("planification_id_calendrier_fk_fkey");

                    b.HasOne("seragenda.Models.CoursNiveau", "IdCoursNiveauFkNavigation")
                        .WithMany("Planifications")
                        .HasForeignKey("IdCoursNiveauFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("planification_id_cours_niveau_fk_fkey");

                    b.Navigation("IdCalendrierFkNavigation");

                    b.Navigation("IdCoursNiveauFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.SeanceObjectif", b =>
                {
                    b.HasOne("seragenda.Models.Planification", "IdPlanningFkNavigation")
                        .WithMany("SeanceObjectifs")
                        .HasForeignKey("IdPlanningFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seance_objectif_id_planning_fk_fkey");

                    b.HasOne("seragenda.Models.Visee", "IdViseeFkNavigation")
                        .WithMany("SeanceObjectifs")
                        .HasForeignKey("IdViseeFk")
                        .IsRequired()
                        .HasConstraintName("seance_objectif_id_visee_fk_fkey");

                    b.Navigation("IdPlanningFkNavigation");

                    b.Navigation("IdViseeFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.SeanceRessource", b =>
                {
                    b.HasOne("seragenda.Models.Chapitre", "IdChapitreFkNavigation")
                        .WithMany("SeanceRessources")
                        .HasForeignKey("IdChapitreFk")
                        .IsRequired()
                        .HasConstraintName("seance_ressource_id_chapitre_fk_fkey");

                    b.HasOne("seragenda.Models.Planification", "IdPlanningFkNavigation")
                        .WithMany("SeanceRessources")
                        .HasForeignKey("IdPlanningFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seance_ressource_id_planning_fk_fkey");

                    b.Navigation("IdChapitreFkNavigation");

                    b.Navigation("IdPlanningFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.Sousdomaine", b =>
                {
                    b.HasOne("seragenda.Models.Domaine", "IdDomFkNavigation")
                        .WithMany("Sousdomaines")
                        .HasForeignKey("IdDomFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sousdomaine_id_dom_fk_fkey");

                    b.Navigation("IdDomFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.UserCourse", b =>
                {
                    b.HasOne("seragenda.Models.Utilisateur", "User")
                        .WithMany()
                        .HasForeignKey("IdUserFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_course_id_user_fk_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("seragenda.Models.UserNote", b =>
                {
                    b.HasOne("seragenda.Models.Utilisateur", "User")
                        .WithMany()
                        .HasForeignKey("IdUserFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_note_id_user_fk_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("seragenda.Models.UtilisationChapitre", b =>
                {
                    b.HasOne("seragenda.Models.Chapitre", "IdChapitreFkNavigation")
                        .WithMany("UtilisationChapitres")
                        .HasForeignKey("IdChapitreFk")
                        .IsRequired()
                        .HasConstraintName("utilisation_chapitre_id_chapitre_fk_fkey");

                    b.HasOne("seragenda.Models.CoursNiveau", "IdCoursNiveauFkNavigation")
                        .WithMany("UtilisationChapitres")
                        .HasForeignKey("IdCoursNiveauFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("utilisation_chapitre_id_cours_niveau_fk_fkey");

                    b.Navigation("IdChapitreFkNavigation");

                    b.Navigation("IdCoursNiveauFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.UtilisationLivre", b =>
                {
                    b.HasOne("seragenda.Models.CoursNiveau", "IdCoursNiveauFkNavigation")
                        .WithMany("UtilisationLivres")
                        .HasForeignKey("IdCoursNiveauFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("utilisation_livre_id_cours_niveau_fk_fkey");

                    b.HasOne("seragenda.Models.Livre", "IdLivreFkNavigation")
                        .WithMany("UtilisationLivres")
                        .HasForeignKey("IdLivreFk")
                        .IsRequired()
                        .HasConstraintName("utilisation_livre_id_livre_fk_fkey");

                    b.Navigation("IdCoursNiveauFkNavigation");

                    b.Navigation("IdLivreFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.Visee", b =>
                {
                    b.HasOne("seragenda.Models.Competence", "IdCompFkNavigation")
                        .WithMany("Visees")
                        .HasForeignKey("IdCompFk")
                        .IsRequired()
                        .HasConstraintName("visees_id_comp_fk_fkey");

                    b.HasOne("seragenda.Models.Domaine", "IdDomaineFkNavigation")
                        .WithMany("Visees")
                        .HasForeignKey("IdDomaineFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visees_id_domaine_fk_fkey");

                    b.HasOne("seragenda.Models.NomVisee", "IdNomViseeFkNavigation")
                        .WithMany("Visees")
                        .HasForeignKey("IdNomViseeFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visees_id_nom_visee_fk_fkey");

                    b.HasOne("seragenda.Models.Sousdomaine", "IdSousDomaineFkNavigation")
                        .WithMany("Visees")
                        .HasForeignKey("IdSousDomaineFk")
                        .HasConstraintName("visees_id_sous_domaine_fk_fkey");

                    b.Navigation("IdCompFkNavigation");

                    b.Navigation("IdDomaineFkNavigation");

                    b.Navigation("IdNomViseeFkNavigation");

                    b.Navigation("IdSousDomaineFkNavigation");
                });

            modelBuilder.Entity("seragenda.Models.Aptitude", b =>
                {
                    b.Navigation("AppartenirViseeAptitudes");
                });

            modelBuilder.Entity("seragenda.Models.CalendrierScolaire", b =>
                {
                    b.Navigation("Planifications");
                });

            modelBuilder.Entity("seragenda.Models.Chapitre", b =>
                {
                    b.Navigation("SeanceRessources");

                    b.Navigation("UtilisationChapitres");
                });

            modelBuilder.Entity("seragenda.Models.Competence", b =>
                {
                    b.Navigation("AppartenirViseeAptitudes");

                    b.Navigation("Visees");
                });

            modelBuilder.Entity("seragenda.Models.Cour", b =>
                {
                    b.Navigation("CoursNiveaus");
                });

            modelBuilder.Entity("seragenda.Models.CoursNiveau", b =>
                {
                    b.Navigation("Domaines");

                    b.Navigation("Planifications");

                    b.Navigation("UtilisationChapitres");

                    b.Navigation("UtilisationLivres");
                });

            modelBuilder.Entity("seragenda.Models.Domaine", b =>
                {
                    b.Navigation("Sousdomaines");

                    b.Navigation("Visees");
                });

            modelBuilder.Entity("seragenda.Models.Livre", b =>
                {
                    b.Navigation("Chapitres");

                    b.Navigation("UtilisationLivres");
                });

            modelBuilder.Entity("seragenda.Models.Niveau", b =>
                {
                    b.Navigation("CoursNiveaus");
                });

            modelBuilder.Entity("seragenda.Models.NomVisee", b =>
                {
                    b.Navigation("Visees");
                });

            modelBuilder.Entity("seragenda.Models.Planification", b =>
                {
                    b.Navigation("SeanceObjectifs");

                    b.Navigation("SeanceRessources");
                });

            modelBuilder.Entity("seragenda.Models.Sousdomaine", b =>
                {
                    b.Navigation("Visees");
                });

            modelBuilder.Entity("seragenda.Models.Utilisateur", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("CoursNiveaus");
                });

            modelBuilder.Entity("seragenda.Models.Visee", b =>
                {
                    b.Navigation("SeanceObjectifs");
                });

            modelBuilder.Entity("seragenda.Models.ViseesMaitriser", b =>
                {
                    b.Navigation("AppartenirViseeAptitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
